// generated by measure_hooks.py — per-image vertical nudge so every hanger hook rests on the rail
export const ROD_FRAC = 0.0967
export const NUDGE: Record<string, number> = {
  'black-coat-back.png': 0.0514,
  'black-coat-side.png': 0.0413,
  'black-coat.png': 0.0518,
  'cream-sweater-back.png': 0.0395,
  'cream-sweater-side.png': 0.0179,
  'cream-sweater.png': 0.0371,
  'green-jacket-back.png': 0.0249,
  'green-jacket-side.png': 0.0348,
  'green-jacket.png': 0.0261,
  'grey-hoodie-back.png': 0.0253,
  'grey-hoodie-side.png': 0.0535,
  'grey-hoodie.png': 0.0254,
  'navy-puffer-back.png': -0.0074,
  'navy-puffer-side.png': 0.0313,
  'navy-puffer.png': -0.0062,
  'white-hoodie-back.png': -0.0023,
  'white-hoodie-side.png': 0.0338,
  'white-hoodie.png': 0.0019,
}
